-- =============================================================================
-- pgTAP — edit token: correcting a declaration you already submitted
-- =============================================================================
-- Verifies migration 20260828000003_registration_edit_handle.sql.
--
-- Why a token at all: fn_create_registration decides "same person" by the
-- DECLARED identity for an unmatched entrant, so re-submitting with a
-- corrected spelling produces a SECOND row rather than fixing the first
-- (proven on LOCAL 2026-08-28: KOWALKSI→row 18, KOWALSKI→row 19, both public).
-- Updating by primary key consults no arbiter, so a correction simply rewrites
-- the row.
--
-- Why the id alone cannot authorise that: id_registration is a column of
-- vw_registration_entry_list — it is not merely enumerable, it is published.
-- The token is the capability, generated by the client and never returned by
-- any public projection.
--
-- The token is a SHORT-LIVED HANDLE, not a stored identity. It lives in the
-- page's memory and is gone when the form unmounts. A fencer returning later
-- re-enters their declared tuple, which upserts onto their row and mints them a
-- fresh handle — so rotation on re-submission is REQUIRED, not incidental:
-- without it a returning fencer could never obtain a usable handle and the
-- correction flow would dead-end.
--
-- The accepted consequence, decided deliberately: anyone who knows a declared
-- name and birth year can obtain the handle for that row and rename it. That is
-- the same population who can already overwrite the entry's weapons and gender
-- through the ordinary upsert, and the birth year is not the secret it appears
-- to be — fn_match_registration_fencer is anon-callable and answers per-year
-- BEFORE any write, so it is already a free, silent oracle. Persisting the token
-- to defend that guessable secret cost a real usability property (localStorage
-- is per-origin and per-device: register on a phone, cannot correct on a laptop)
-- and was rejected on that trade.
-- =============================================================================

BEGIN;

SELECT plan(14);

-- 59.1 — the column exists
SELECT has_column('tbl_registration', 'uuid_edit_token', '59.1 — tbl_registration.uuid_edit_token exists');

-- 59.2 — and is NOT published. The whole scheme collapses if it leaks.
SELECT ok(
  NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_name = 'vw_registration_entry_list'
       AND column_name = 'uuid_edit_token'
  ),
  '59.2 — the token is NOT exposed by the public entry-list view'
);

SELECT has_function('fn_update_registration', '59.3 — fn_update_registration() exists');

-- The read-back RPC that existed in an earlier draft is deliberately gone: with
-- no persistence the fencer retypes their declaration, so it had no caller, and
-- an anon-callable SECURITY DEFINER function with no caller is exactly the
-- surface ADR-083's deny-by-default posture exists to prevent.
SELECT ok(
  NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'fn_get_registration'),
  '59.3b — fn_get_registration is not present (no caller, no surface)'
);

DO $setup$
DECLARE v_season INT; v_org INT;
BEGIN
  v_season := fn_create_season('REG59', '2098-09-01', '2099-06-30');
  INSERT INTO tbl_organizer (txt_code, txt_name)
    VALUES ('REGORG59', 'Reg org 59') RETURNING id_organizer INTO v_org;
  PERFORM fn_create_event('REG59EVT', 'Reg 59', v_season, v_org);
END $setup$;

-- ---------------------------------------------------------------------------
-- The fencer registers, misspelling their own surname, supplying a token.
-- ---------------------------------------------------------------------------
DO $register$
DECLARE v_e INT; v_id INT;
BEGIN
  SELECT id_event INTO v_e FROM tbl_event WHERE txt_code = 'REG59EVT';
  v_id := fn_create_registration(v_e,'KOWALKSI','Adam','M',1968::SMALLINT,
            ARRAY['EPEE']::enum_weapon_type[], NULL, NULL, 'v1.0',
            '11111111-1111-1111-1111-111111111111'::UUID);
  CREATE TEMP TABLE t59 AS SELECT v_id AS id, v_e AS ev;
END $register$;

SELECT is(
  (SELECT uuid_edit_token FROM tbl_registration WHERE id_registration = (SELECT id FROM t59)),
  '11111111-1111-1111-1111-111111111111'::UUID,
  '59.4 — the client-supplied token is stored on the row'
);

-- 59.5 — a re-submission that carries no token must not erase the existing one
DO $resubmit$
DECLARE v_e INT;
BEGIN
  SELECT ev INTO v_e FROM t59;
  PERFORM fn_create_registration(v_e,'KOWALKSI','Adam','M',1968::SMALLINT,
            ARRAY['EPEE','SABRE']::enum_weapon_type[], NULL, NULL, NULL, NULL);
END $resubmit$;

SELECT is(
  (SELECT uuid_edit_token FROM tbl_registration WHERE id_registration = (SELECT id FROM t59)),
  '11111111-1111-1111-1111-111111111111'::UUID,
  '59.5 — a re-submission without a token keeps the one already stored'
);

-- 59.5b — but a re-submission that DOES supply a token takes ownership of the
-- row. This is the mechanism that makes a correction possible after the handle
-- is gone: the fencer returns, re-enters the tuple they submitted, and is handed
-- a working handle for their own row. It necessarily also means anyone who knows
-- that tuple can obtain the handle — accepted deliberately (see the header).
DO $rotate$
DECLARE v_e INT;
BEGIN
  SELECT ev INTO v_e FROM t59;
  PERFORM fn_create_registration(v_e,'KOWALKSI','Adam','M',1968::SMALLINT,
            ARRAY['EPEE']::enum_weapon_type[], NULL, NULL, NULL,
            '99999999-9999-9999-9999-999999999999'::UUID);
END $rotate$;

SELECT is(
  (SELECT uuid_edit_token FROM tbl_registration WHERE id_registration = (SELECT id FROM t59)),
  '99999999-9999-9999-9999-999999999999'::UUID,
  '59.5b — re-submitting the declared tuple mints a fresh handle for that row'
);

SELECT is(
  (SELECT count(*)::INT FROM tbl_registration r JOIN tbl_event e USING (id_event)
    WHERE e.txt_code='REG59EVT' AND r.txt_first_name='Adam'),
  1,
  '59.5c — and re-submitting still upserts, never adding a second row'
);

-- 59.6 — the wrong token is refused
SELECT throws_ok(
  format($$SELECT fn_update_registration(%s, '22222222-2222-2222-2222-222222222222'::UUID,
            'KOWALSKI'::TEXT, 'Adam'::TEXT, 'M'::enum_gender_type, 1968::SMALLINT,
            ARRAY['EPEE']::enum_weapon_type[])$$, (SELECT id FROM t59)),
  NULL, NULL,
  '59.6 — a wrong edit token is refused'
);

-- 59.7 — and so is a missing one
SELECT throws_ok(
  format($$SELECT fn_update_registration(%s, NULL::UUID,
            'KOWALSKI'::TEXT, 'Adam'::TEXT, 'M'::enum_gender_type, 1968::SMALLINT,
            ARRAY['EPEE']::enum_weapon_type[])$$, (SELECT id FROM t59)),
  NULL, NULL,
  '59.7 — a NULL edit token is refused'
);

-- ---------------------------------------------------------------------------
-- 59.8–59.9 — the correction itself: the surname is fixed IN PLACE
-- ---------------------------------------------------------------------------
DO $correct$
DECLARE v_id INT;
BEGIN
  SELECT id INTO v_id FROM t59;
  PERFORM fn_update_registration(v_id, '99999999-9999-9999-9999-999999999999'::UUID,
            'KOWALSKI','Adam','M',1968::SMALLINT, ARRAY['EPEE','SABRE']::enum_weapon_type[]);
END $correct$;

SELECT is(
  (SELECT count(*)::INT FROM tbl_registration r JOIN tbl_event e USING (id_event)
    WHERE e.txt_code='REG59EVT' AND r.txt_first_name='Adam'),
  1,
  '59.8 — correcting the spelling leaves ONE row, not a second entry'
);

SELECT is(
  (SELECT txt_surname FROM tbl_registration WHERE id_registration = (SELECT id FROM t59)),
  'KOWALSKI',
  '59.9 — and that row now carries the corrected surname'
);

-- 59.10 — consent evidence is not disturbed by an edit. Consent was given at
-- submission; correcting a typo is not a new consent event.
SELECT isnt(
  (SELECT ts_consent FROM tbl_registration WHERE id_registration = (SELECT id FROM t59)),
  NULL,
  '59.10 — the consent stamp survives an edit'
);

-- 59.11 — a correction that would collide with another entrant fails loudly
-- rather than silently destroying or duplicating either row.
DO $rival$
DECLARE v_e INT;
BEGIN
  SELECT ev INTO v_e FROM t59;
  PERFORM fn_create_registration(v_e,'NOWAK','Adam','M',1968::SMALLINT,
            ARRAY['EPEE']::enum_weapon_type[], NULL, NULL, 'v1.0',
            '33333333-3333-3333-3333-333333333333'::UUID);
END $rival$;

SELECT throws_ok(
  format($$SELECT fn_update_registration(%s, '99999999-9999-9999-9999-999999999999'::UUID,
            'NOWAK'::TEXT, 'Adam'::TEXT, 'M'::enum_gender_type, 1968::SMALLINT,
            ARRAY['EPEE']::enum_weapon_type[])$$, (SELECT id FROM t59)),
  NULL, NULL,
  '59.11 — editing into another entrant''s identity is refused, not merged'
);

-- ---------------------------------------------------------------------------
SELECT * FROM finish();

ROLLBACK;
