-- Snapshot of tbl_season + tbl_event from LOCAL DB
-- Generated: 2026-05-03T11:30:26.494522Z
-- Idempotent: uses INSERT ... ON CONFLICT DO UPDATE
-- Loaded by supabase/config.toml [db.seed].sql_paths after seed_prod_latest.sql

BEGIN;

-- ========== tbl_season ==========
INSERT INTO tbl_season (bool_active, dt_end, dt_start, enum_carryover_engine, id_season, int_carryover_days, ts_created, txt_code) VALUES (FALSE, '2024-07-15', '2023-01-01', 'EVENT_CODE_MATCHING', 1, 366, '2026-05-03T11:08:52.573806+00:00', 'SPWS-2023-2024')
  ON CONFLICT (id_season) DO UPDATE SET bool_active=EXCLUDED.bool_active, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_carryover_engine=EXCLUDED.enum_carryover_engine, int_carryover_days=EXCLUDED.int_carryover_days, ts_created=EXCLUDED.ts_created, txt_code=EXCLUDED.txt_code;
INSERT INTO tbl_season (bool_active, dt_end, dt_start, enum_carryover_engine, id_season, int_carryover_days, ts_created, txt_code) VALUES (FALSE, '2025-07-15', '2024-08-15', 'EVENT_CODE_MATCHING', 2, 366, '2026-05-03T11:08:52.573806+00:00', 'SPWS-2024-2025')
  ON CONFLICT (id_season) DO UPDATE SET bool_active=EXCLUDED.bool_active, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_carryover_engine=EXCLUDED.enum_carryover_engine, int_carryover_days=EXCLUDED.int_carryover_days, ts_created=EXCLUDED.ts_created, txt_code=EXCLUDED.txt_code;
INSERT INTO tbl_season (bool_active, dt_end, dt_start, enum_carryover_engine, id_season, int_carryover_days, ts_created, txt_code) VALUES (TRUE, '2026-07-15', '2025-08-01', 'EVENT_CODE_MATCHING', 3, 366, '2026-05-03T11:08:52.573806+00:00', 'SPWS-2025-2026')
  ON CONFLICT (id_season) DO UPDATE SET bool_active=EXCLUDED.bool_active, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_carryover_engine=EXCLUDED.enum_carryover_engine, int_carryover_days=EXCLUDED.int_carryover_days, ts_created=EXCLUDED.ts_created, txt_code=EXCLUDED.txt_code;

-- ========== tbl_event ==========
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2022-01-08', '2022-01-08', 'COMPLETED', 1, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW2e-2023-2024', 'PEW2', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-06-18', '2022-06-18', 'COMPLETED', 2, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'GP3-2023-2024', 'Polska', 'PLN', 'Niepołomice', 'GP3', 'ENGINE_COMPUTED', 'https://www.fencingtimelive.com/tournaments/eventSchedule/A233DC1D44A44F6CBC3CF3E9D9BDFBFA#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-01-01', '2023-01-01', 'COMPLETED', 3, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'IMEW-2023-2024', 'IMEW', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-01-08', '2023-01-07', 'COMPLETED', 4, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW1e-2023-2024', 'Great Britain', 'Guilford', 'PEW1', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/A49E0E562CE6460B82AACFD5C909F0BE#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-01-15', '2023-01-14', 'COMPLETED', 5, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'GP1-2023-2024', 'Polska', 'PLN', 'Pabianice', 'GP1', 'ENGINE_COMPUTED', 'https://www.fencingtimelive.com/tournaments/eventSchedule/B3DA380CD665461DA7201E30A5652557#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-02-12', '2023-02-12', 'COMPLETED', 6, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW3s-2023-2024', 'PEW3', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-05-03', '2023-03-04', 'COMPLETED', 7, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'GP2-2023-2024', 'Polska', 'PLN', 'Toruń', 'GP2', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/4A559DB9F1984325A771A6255602D540#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-03-18', '2023-03-18', 'COMPLETED', 8, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW4f-2023-2024', 'PEW4', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-03-23', '2023-03-23', 'COMPLETED', 9, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW12f-2023-2024', 'PEW12', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-07-07', '2023-07-07', 'COMPLETED', 10, 3, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'VFC-2023-2024', 'VFC', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-09-16', '2023-09-16', 'COMPLETED', 11, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW5fs-2023-2024', 'PEW5', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-10-09', '2023-10-09', 'COMPLETED', 12, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW7s-2023-2024', 'PEW7', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-09-24', '2023-09-23', 'COMPLETED', 13, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:12:46.729378+00:00', 'GP4-2023-2024', 'Polska', 'PLN', 'Opole', 'GP4', 'ENGINE_COMPUTED', 'https://www.fencingtimelive.com/tournaments/eventSchedule/4E8236D593B64434A9EE99D9B5F7E65F#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-10-28', '2023-10-28', 'COMPLETED', 14, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'GP5-2023-2024', 'Polska', 'PLN', 'Gdańsk', 'GP5', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/B039D94D12F243B1961DEA9CAB298A40#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-11-11', '2023-11-11', 'COMPLETED', 15, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW6efs-2023-2024', 'PEW6', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-11-18', '2023-11-18', 'COMPLETED', 16, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:15:00.916759+00:00', 'GP6-2023-2024', 'Polska', 'PLN', 'Kraków', 'GP6', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/D70668CEB8754915920393A22468C3AB#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-12-16', '2023-12-16', 'COMPLETED', 17, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW8fs-2023-2024', 'PEW8', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-02-24', '2024-01-06', 'COMPLETED', 18, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW9e-2023-2024', 'Great Britain', 'Guildford', 'PEW9', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/1B776AA923B64D3FA61AB02233AF54BD#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-03-23', '2024-01-20', 'COMPLETED', 19, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW10s-2023-2024', 'PEW10', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-01-28', '2024-01-27', 'COMPLETED', 20, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:17:21.313057+00:00', 'GP7-2023-2024', 'Polska', 'PLN', 'Spała', 'GP7', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/85A647ED7CA8457AAB73EFA286767B15#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-02-24', '2024-02-24', 'COMPLETED', 21, 1, 1, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW11f-2023-2024', 'PEW11', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-03-02', '2024-03-02', 'COMPLETED', 22, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'MPW-2023-2024', 'Polska', 'PLN', 'Warszawa', 'MPW', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-06-22', '2024-06-22', 'COMPLETED', 23, 3, 1, 100, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:18:38.905651+00:00', 'GP8-2023-2024', 'Polska', 'PLN', 'Niepołomice', 'GP8', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/3D4AE99A80D04D30A3C8B870E292FAD3#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-12-08', '2024-12-07', 'COMPLETED', 24, 1, 6, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW3fs-2024-2025', 'Germany', 'Munich', 'PEW3', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/9CC8D1BC59084DC0852659F9B68D97DB#today')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_location, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-09-22', '2024-09-21', 'COMPLETED', 25, 1, 4, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW1efs-2024-2025', 'PLN', 'Budapest', 'PEW1', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-09-29', '2024-09-28', 'COMPLETED', 26, 3, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW1-2024-2025', 'Polska', 'Konin', 'I Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://weteraniszermierki.pl/i-puchar-pokski-weteranow-sezon-2024-2025-serdecznie-zapraszamy-na-pierwszy-puchar-polski-weteranow/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-10-27', '2024-10-26', 'COMPLETED', 27, 3, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW2-2024-2025', 'Polska', 'Bytom', 'II Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://weteraniszermierki.pl/ii-puchar-polski-weteranow-bytom-2024/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_location, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-11-17', '2024-11-16', 'COMPLETED', 28, 1, 1, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW2efs-2024-2025', 'PLN', 'Madrid', 'PEW2', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-12-01', '2024-11-30', 'COMPLETED', 29, 3, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW3-2024-2025', 'Polska', 'Kraków', 'III Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://weteraniszermierki.pl/iii-puchar-polski-weteranow-krakow-2024/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-01-05', '2025-01-05', 'COMPLETED', 30, 1, 8, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW4f-2024-2025', 'PEW4', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-01-18', '2025-01-18', 'COMPLETED', 31, 1, 11, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW5s-2024-2025', 'PEW5', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-02-02', '2025-02-02', 'COMPLETED', 32, 1, 15, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW6fs-2024-2025', 'PEW6', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-02-23', '2025-02-22', 'COMPLETED', 33, 3, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW4-2024-2025', 'Polska', 'Warszawa', 'IV Puchar Polski Weteranów - Memoriał Gen. Jerzego Zabielskiego', 'ENGINE_COMPUTED', 'https://weteraniszermierki.pl/iv-puchar-polski-weteranow-memorial-gen-jerzego-zabielskiego/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-03-29', '2025-03-29', 'COMPLETED', 34, 1, 12, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW7s-2024-2025', 'PEW7', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-04-12', '2025-03-30', 'COMPLETED', 35, 1, 17, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW8f-2024-2025', 'PEW8', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-04-27', '2025-04-26', 'COMPLETED', 36, 3, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW5-2024-2025', 'Polska', 'Szczecin', 'V Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://weteraniszermierki.pl/wp-content/uploads/2025/03/KOMUNIKAT-2-V-PP-SZCZECIN-2025_1.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-05-03', '2025-05-03', 'COMPLETED', 37, 1, 18, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW9-2024-2025', 'PEW9', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-06-01', '2025-05-28', 'COMPLETED', 38, 1, 3, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'IMEW-2024-2025', 'Bulgaria', 'Plovdiv', 'European Veterans Championships 2025', 'ENGINE_COMPUTED', 'https://www.veteransfencing.eu/wp-content/uploads/2025/04/invitation-ECH.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-06-08', '2025-06-07', 'COMPLETED', 39, 3, 22, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'MPW-2024-2025', 'Polska', 'Pabianice', 'XXXIV Indywidualne Mistrzostwa Polski Weteranów', 'ENGINE_COMPUTED', 'https://www.fencingtimelive.com/tournaments/eventSchedule/B2C615704AB84D0F85BBFF395C07BA41#today', 'https://weteraniszermierki.pl/xxxiv-indywidualne-mistrzostwa-polski-weteranow-lodz-2025/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-07-05', '2025-07-05', 'COMPLETED', 40, 1, 19, 2, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW10efs-2024-2025', 'France', 'Paris', 'EVF Criterium Mondial Vétérans 2025', 'ENGINE_COMPUTED', 'https://engarde-service.com/tournament/fencingaddict/crit25')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_event_2, url_event_3, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-09-21', '2025-09-20', 'COMPLETED', 41, 1, 25, 3, 45, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW1efs-2025-2026', 'Hungary', 'EUR', 'Budapest', 'EVF Circuit Budapest', 'ENGINE_COMPUTED', 'Istvánmezei út 3-5., Budapest, Hungary', 'https://engarde-service.com/tournament/hunfencing/2025_09_20_pbt', 'https://engarde-service.com/tournament/hunfencing/2025_09_21_tor', 'https://engarde-service.com/tournament/hunfencing/2025_09_21_kard', 'https://www.veteransfencing.eu/wp-content/uploads/2025/08/International-Veteran-Budapest-Cup-event-2025-september-ENG.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_event_2=EXCLUDED.url_event_2, url_event_3=EXCLUDED.url_event_3, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-09-28', '2025-09-27', 'COMPLETED', 42, 3, 26, 3, 250, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW1-2025-2026', 'Polska', 'PLN', 'Opole', 'I Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/BF6E1ADD88844A8CAC2F8CD353D082F9#today', 'https://weteraniszermierki.pl/zaproszenie-na-i-puchar-polski-weteranow-szermierki-opole-2025/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-10-26', '2025-10-25', 'COMPLETED', 43, 3, 27, 3, 250, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW2-2025-2026', 'Polska', 'PLN', 'Poznań', 'II Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/BC4FAB2F4A5E466DAA8FC46EB73E50F6#today', 'https://weteraniszermierki.pl/wp-content/uploads/2025/10/Komunikat-zawodow-Poznan-2.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation, url_registration) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-11-02', '2025-11-01', 'COMPLETED', 44, 1, 28, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW2efs-2025-2026', 'Spain', 'PLN', 'Madrid', 'EVF Circuit Madrid', 'ENGINE_COMPUTED', 'C/ de Valdebernardo, 2, Madrid, Spain', 'https://engarde-service.com/tournament/aeve_esgrima/evf_madrid_2025', 'https://www.veteransfencing.eu/wp-content/uploads/2025/10/EVF-Circuit-Madrid-2025.pdf', 'https://aevesgrima.es/inscripciones-madrid-2025/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation, url_registration=EXCLUDED.url_registration;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-12-06', '2025-12-06', 'COMPLETED', 45, 1, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW21fs-2025-2026', 'Germany', 'PLN', 'Munich', 'EVF Circuit Memoriam Max Geuter - Munich (GER)', 'ENGINE_COMPUTED', 'Riesstrasse 40, Munich, Germany', 'https://www.veteransfencing.eu/event/evf-circuit-munich/', 'https://www.veteransfencing.eu/wp-content/uploads/2025/10/Ausschreibung-englisch-5.8.25.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-12-14', '2025-12-13', 'COMPLETED', 46, 3, 29, 3, 250, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW3-2025-2026', 'Polska', 'PLN', 'Warszawa-Łomianki', 'III Puchar Polski Weteranów / Warsaw Epee Open', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/D099355BC4334343949BD91172023B49#today', 'https://weteraniszermierki.pl/zaproszenie-na-iii-puchar-polski-weteranow-szermierki-warsaw-epee-open-2025/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-12-06', '2025-12-06', 'COMPLETED', 47, 1, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW3s-2025-2026', 'Germany', 'PLN', 'Munich', 'EVF Circuit Guildford', 'ENGINE_COMPUTED', 'Parkway, Guildford, United Kingdom', 'https://fencingtimelive.com/tournaments/eventSchedule/E2A7B077F2824DD8A7F2E413B4211296#today', 'https://www.veteransfencing.eu/wp-content/uploads/2025/10/EVf-Guildford-2026-invitation-letter.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-02-07', '2026-02-07', 'COMPLETED', 48, 1, 3, 45.0, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW31fs-2025-2026', 'France', 'PLN', 'Faches', 'EVF Circuit - Faches-Thumesnil (FRA)', 'ENGINE_COMPUTED', '7, rue de la Linière, Fâches-Thumesnil, France', 'https://www.veteransfencing.eu/event/evf-circuit-faches/', 'https://www.veteransfencing.eu/wp-content/uploads/2025/11/Circuit-europeen-veteran-Faches-7-et-8-fevrier-2026-EN.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-02-22', '2026-02-21', 'COMPLETED', 49, 3, 33, 3, 250, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW4-2025-2026', 'Polska', 'PLN', 'Gdańsk', 'IV Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://fencingtimelive.com/tournaments/eventSchedule/D586C1250E8C41D3BB9B9E5772CB998F#today', 'https://weteraniszermierki.pl/zaproszenie-na-iv-puchar-polski-weteranow-szermierki-gdansk-2026/')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-03-07', '2026-03-07', 'COMPLETED', 50, 1, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW4efs-2025-2026', 'Italy', 'Napoli', 'EVF Circuit Napoli', 'ENGINE_COMPUTED', 'https://www.4fence.it/FIS/Risultati/2026-03-08-07_Napoli_-_4_Prova_Circuito_Nazionale_Master_2025-2/', 'https://www.veteransfencing.eu/wp-content/uploads/2026/01/EVF-Circuit-Napoli-7-and-8-mar26-ENG.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation, url_registration) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-02-07', '2026-02-07', 'COMPLETED', 51, 1, 31, 3, 50.0, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW5s-2025-2026', 'Sweden', 'Stockholm', 'EVF Circuit Stockholm', 'ENGINE_COMPUTED', 'Mosskroken 11, Bromma, Sweden', 'https://engarde-service.com/tournament/sthlm/vet2026', 'https://www.veteransfencing.eu/wp-content/uploads/2023/05/Invitation-EVF-Stockholm-2026.pdf', 'https://fencing.ophardt.online/sv/widget/event/32815')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation, url_registration=EXCLUDED.url_registration;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-03-29', '2026-03-28', 'COMPLETED', 52, 1, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW6efs-2025-2026', 'Polska', 'Jabłonna', 'EVF Circuit Jabłonna', 'ENGINE_COMPUTED', 'https://www.fencingtimelive.com/tournaments/eventSchedule/98F13C10A47B49FFA2D39E4D47F1EDA8#today', 'https://www.veteransfencing.eu/wp-content/uploads/2026/02/62c4d775-86d2-454c-9b61-c999e8d24791.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation) VALUES (ARRAY['SABRE'], '2026-04-11', '2026-04-11', 'COMPLETED', 53, 1, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW61s-2025-2026', 'Belgium', 'EUR', 'Liège', 'EVF Circuit – Liège (BEL)', 'ENGINE_COMPUTED', 'Rue Ernest Malvoz 31, Liège, Belgium', 'https://www.veteransfencing.eu/event/evf-circuit-liege/', 'https://www.veteransfencing.eu/wp-content/uploads/2026/03/httpsforms.glePZmcphR6ViHZRUR56.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-04-11', '2026-04-11', 'COMPLETED', 54, 3, 36, 3, 250, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PPW5-2025-2026', 'Polska', 'PLN', 'Gdańsk', 'V Puchar Polski Weteranów', 'ENGINE_COMPUTED', 'https://weteraniszermierki.pl/wp-content/uploads/2026/03/Komunikat-organizacyjny-V-Pucharu-Polski-Weteranow-Szermierki_Gdansk_11_kwietnia_2026.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_registration_deadline, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation, url_registration) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-04-19', '2026-04-11', '2026-04-18', 'COMPLETED', 55, 1, 3, 50.0, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW7ef-2025-2026', 'Austria', 'PLN', 'Salzburg', 'EVF Circuit Salzburg', 'ENGINE_COMPUTED', 'Schießstattstraße 26, Salzburg,, Austria', 'https://dartagnan.live/turniere/EuropeanVeteransCup_2026/de/index.html', 'https://www.veteransfencing.eu/wp-content/uploads/2026/03/EVC-Salzburg-Ausschreibung-2026_Aktuell-1.pdf', 'https://forms.gle/dpmjFjo8JRr7KvsJA')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_registration_deadline=EXCLUDED.dt_registration_deadline, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation, url_registration=EXCLUDED.url_registration;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_registration_deadline, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-03-29', '2026-04-25', '2025-03-29', 'PLANNED', 56, 1, 35, 3, 45, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW8f-2025-2026', 'Greece', 'PLN', 'Chania', 'EVF Circuit Chania', 'ENGINE_COMPUTED', 'Marinou Antipa 10, Chania, Crete, Greece', 'https://www.veteransfencing.eu/event/evf-circuit-athens-gre/', 'https://www.veteransfencing.eu/wp-content/uploads/2026/03/Chania-Invitation-letter-2026.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_registration_deadline=EXCLUDED.dt_registration_deadline, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_registration_deadline, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-05-14', '2026-04-14', '2026-05-14', 'PLANNED', 57, 1, 3, 450.0, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'DMEW-2025-2026', 'France', 'PLN', 'Complexe Sportif Omnisports des Vauzelles', 'European Team Championships 2026 – Cognac', 'ENGINE_COMPUTED', '19 rue des Vauzelles, Chateaubernard, France', 'https://www.veteransfencing.eu/event/european-team-championships-2026-cognac-fr/', 'https://www.veteransfencing.eu/wp-content/uploads/2025/09/Affiche-Europe-2026-Cognac-V3.pdf')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_registration_deadline=EXCLUDED.dt_registration_deadline, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_registration_deadline, dt_start, enum_status, id_event, id_organizer, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status, txt_venue_address, url_event, url_invitation, url_registration) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-05-31', '2026-05-15', '2026-05-30', 'PLANNED', 58, 1, 3, 40, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'PEW9efs-2025-2026', 'Ireland', 'PLN', 'Dublin', 'EVF Circuit Dublin', 'ENGINE_COMPUTED', 'UCD Sport Center Belfield Dublin, Dublin, Ireland', 'https://www.veteransfencing.eu/event/evf-circuit-dublin-irl/', 'https://www.veteransfencing.eu/wp-content/uploads/2026/02/VIO-2026-Invitation-Letter.pdf', 'https://forms.cloud.microsoft/pages/responsepage.aspx?id=eRfaQEG0lUeDESRi15GFbwVSwCeGdX9PgnwKqAvTSyBURE1YTEJLNEJFQjc0SFdFS0Y1WUVZR004Sy4u&route=shorturl')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_registration_deadline=EXCLUDED.dt_registration_deadline, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status, txt_venue_address=EXCLUDED.txt_venue_address, url_event=EXCLUDED.url_event, url_invitation=EXCLUDED.url_invitation, url_registration=EXCLUDED.url_registration;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, num_entry_fee, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-06-21', '2026-06-20', 'SCHEDULED', 59, 3, 39, 3, 250, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'MPW-2025-2026', 'Polska', 'PLN', 'Warszawa', 'MPW', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, num_entry_fee=EXCLUDED.num_entry_fee, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_location, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-10-18', '2026-10-11', 'PLANNED', 60, 2, 3, '2026-05-03T11:08:52.573806+00:00', '2026-05-03T11:08:52.573806+00:00', 'IMSW-2025-2026', 'Gruzja', 'Tbilisi', 'IMSW', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-04-06', '2024-04-06', 'COMPLETED', 61, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW13e-2023-2024', 'PLN', 'PEW13-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-04-06', '2024-04-06', 'COMPLETED', 62, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW14s-2023-2024', 'PLN', 'PEW14-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-04-27', '2024-04-27', 'COMPLETED', 63, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW15e-2023-2024', 'PLN', 'PEW15-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2022-02-25', '2022-02-25', 'COMPLETED', 64, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW16e-2023-2024', 'PLN', 'PEW16-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-01-21', '2023-01-21', 'COMPLETED', 65, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW17fs-2023-2024', 'PLN', 'PEW17-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-02-25', '2023-02-25', 'COMPLETED', 66, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW18e-2023-2024', 'PLN', 'PEW18-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-04-15', '2023-04-14', 'COMPLETED', 67, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW19e-2023-2024', 'PLN', 'PEW19-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-04-01', '2023-04-01', 'COMPLETED', 68, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW20s-2023-2024', 'PLN', 'PEW20-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-09-16', '2023-09-16', 'COMPLETED', 69, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW21e-2023-2024', 'PLN', 'PEW21-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-09-24', '2023-09-24', 'COMPLETED', 70, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW22e-2023-2024', 'PLN', 'PEW22-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-12-09', '2023-12-09', 'COMPLETED', 71, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW23f-2023-2024', 'PLN', 'PEW23-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2023-12-16', '2023-12-16', 'COMPLETED', 72, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW24e-2023-2024', 'PLN', 'PEW24-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2024-01-06', '2024-01-06', 'COMPLETED', 73, 1, 1, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW25e-2023-2024', 'PLN', 'PEW25-2023-2024', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_country, txt_entry_fee_currency, txt_location, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-01-04', '2025-01-04', 'COMPLETED', 74, 1, 2, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW11e-2024-2025', 'Great Britain', 'PLN', 'Guildford', 'PEW11-2024-2025', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_country=EXCLUDED.txt_country, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_location=EXCLUDED.txt_location, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-02-02', '2025-02-01', 'COMPLETED', 75, 1, 2, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW12e-2024-2025', 'PLN', 'PEW12-2024-2025', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_prior_event, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-03-15', '2025-03-15', 'COMPLETED', 76, 1, 61, 2, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW13e-2024-2025', 'PLN', 'PEW13-2024-2025', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_prior_event=EXCLUDED.id_prior_event, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-03-29', '2025-03-29', 'COMPLETED', 77, 1, 2, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW14e-2024-2025', 'PLN', 'PEW14-2024-2025', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2025-05-15', '2025-05-15', 'COMPLETED', 78, 1, 2, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW15f-2024-2025', 'PLN', 'PEW15-2024-2025', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-01-11', '2026-01-10', 'COMPLETED', 79, 1, 3, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW62efs-2025-2026', 'PLN', 'PEW62-2025-2026', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-10-01', '2026-10-01', 'COMPLETED', 80, 1, 3, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW63e-2025-2026', 'PLN', 'PEW63-2025-2026', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-11-11', '2026-11-11', 'COMPLETED', 81, 1, 3, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW64s-2025-2026', 'PLN', 'PEW64-2025-2026', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-03-14', '2026-03-14', 'COMPLETED', 82, 1, 3, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW65ef-2025-2026', 'PLN', 'PEW65-2025-2026', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-03-29', '2026-03-29', 'COMPLETED', 83, 1, 3, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW66f-2025-2026', 'PLN', 'PEW66-2025-2026', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;
INSERT INTO tbl_event (arr_weapons, dt_end, dt_start, enum_status, id_event, id_organizer, id_season, ts_created, ts_updated, txt_code, txt_entry_fee_currency, txt_name, txt_source_status) VALUES (ARRAY['EPEE','FOIL','SABRE'], '2026-05-02', '2026-05-02', 'COMPLETED', 84, 1, 3, '2026-05-03T11:08:52.909714+00:00', '2026-05-03T11:08:52.909714+00:00', 'PEW67f-2025-2026', 'PLN', 'PEW67-2025-2026', 'ENGINE_COMPUTED')
  ON CONFLICT (id_event) DO UPDATE SET arr_weapons=EXCLUDED.arr_weapons, dt_end=EXCLUDED.dt_end, dt_start=EXCLUDED.dt_start, enum_status=EXCLUDED.enum_status, id_organizer=EXCLUDED.id_organizer, id_season=EXCLUDED.id_season, ts_created=EXCLUDED.ts_created, ts_updated=EXCLUDED.ts_updated, txt_code=EXCLUDED.txt_code, txt_entry_fee_currency=EXCLUDED.txt_entry_fee_currency, txt_name=EXCLUDED.txt_name, txt_source_status=EXCLUDED.txt_source_status;

-- Reset sequences past the snapshot
SELECT setval(pg_get_serial_sequence('tbl_event', 'id_event'), (SELECT COALESCE(MAX(id_event),1) FROM tbl_event));
SELECT setval(pg_get_serial_sequence('tbl_season', 'id_season'), (SELECT COALESCE(MAX(id_season),1) FROM tbl_season));

COMMIT;