-- =========================================================================
-- Event metadata for season 2024-2025
-- Auto-generated by staging_spreadsheet.py export mode.
-- Loaded AFTER per-category v*.sql files (zz_ prefix ensures ordering).
-- Phase 1: INSERT events not yet created by result files.
-- Phase 2: UPDATE all events with enriched metadata.
-- =========================================================================

-- Phase 1: Ensure all events exist
INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW1-2024-2025',
    'I Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW1-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW2-2024-2025',
    'II Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW2-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW3-2024-2025',
    'III Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW3-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW4-2024-2025',
    'IV Puchar Polski Weteranów - Memoriał Gen. Jerzego Zabielskiego',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW4-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW5-2024-2025',
    'V Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW5-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'MPW-2024-2025',
    'XXXIV Indywidualne Mistrzostwa Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'MPW-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW1-2024-2025',
    'PEW1',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW1-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW2-2024-2025',
    'PEW2',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW2-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW3-2024-2025',
    'PEW3',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW3-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW4-2024-2025',
    'PEW4',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW4-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW5-2024-2025',
    'PEW5',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW5-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW6-2024-2025',
    'PEW6',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW6-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW7-2024-2025',
    'PEW7',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW7-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW8-2024-2025',
    'PEW8',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW8-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'IMEW-2024-2025',
    'European Veterans Championships 2025',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'IMEW-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PS-2024-2025',
    'PS',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'FIE'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PS-2024-2025');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW9-2024-2025',
    'PEW9',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2024-2025'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW9-2024-2025');

-- Phase 2: Update events with enriched metadata
UPDATE tbl_event SET
    txt_name = 'I Puchar Polski Weteranów',
    txt_location = 'Konin',
    txt_country = 'Polska',
    dt_start = '2024-09-28',
    dt_end = '2024-09-29',
    url_event = NULL,
    url_invitation = 'https://weteraniszermierki.pl/i-puchar-pokski-weteranow-sezon-2024-2025-serdecznie-zapraszamy-na-pierwszy-puchar-polski-weteranow/',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PPW1-2024-2025';

UPDATE tbl_event SET
    txt_name = 'II Puchar Polski Weteranów',
    txt_location = 'Bytom',
    txt_country = 'Polska',
    dt_start = '2024-10-26',
    dt_end = '2024-10-27',
    url_event = NULL,
    url_invitation = 'https://weteraniszermierki.pl/ii-puchar-polski-weteranow-bytom-2024/',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PPW2-2024-2025';

UPDATE tbl_event SET
    txt_name = 'III Puchar Polski Weteranów',
    txt_location = 'Kraków',
    txt_country = 'Polska',
    dt_start = '2024-11-30',
    dt_end = '2024-12-01',
    url_event = NULL,
    url_invitation = 'https://weteraniszermierki.pl/iii-puchar-polski-weteranow-krakow-2024/',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PPW3-2024-2025';

UPDATE tbl_event SET
    txt_name = 'IV Puchar Polski Weteranów - Memoriał Gen. Jerzego Zabielskiego',
    txt_location = 'Warszawa',
    txt_country = 'Polska',
    dt_start = '2025-02-22',
    dt_end = '2025-02-23',
    url_event = NULL,
    url_invitation = 'https://weteraniszermierki.pl/iv-puchar-polski-weteranow-memorial-gen-jerzego-zabielskiego/',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PPW4-2024-2025';

UPDATE tbl_event SET
    txt_name = 'V Puchar Polski Weteranów',
    txt_location = 'Szczecin',
    txt_country = 'Polska',
    dt_start = '2025-04-26',
    dt_end = '2025-04-27',
    url_event = 'https://www.fencingtimelive.com/tournaments/eventSchedule/705DF0675003488FBF0F493E76892123',
    url_invitation = 'https://weteraniszermierki.pl/wp-content/uploads/2025/03/KOMUNIKAT-2-V-PP-SZCZECIN-2025_1.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PPW5-2024-2025';

UPDATE tbl_event SET
    txt_name = 'XXXIV Indywidualne Mistrzostwa Polski Weteranów',
    txt_location = 'Pabianice',
    txt_country = 'Polska',
    dt_start = '2025-06-07',
    dt_end = '2025-06-08',
    url_event = NULL,
    url_invitation = 'https://weteraniszermierki.pl/xxxiv-indywidualne-mistrzostwa-polski-weteranow-lodz-2025/',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'MPW-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW1',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2024-09-21',
    dt_end = '2024-09-22',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW1-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW2',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2024-11-16',
    dt_end = '2024-11-17',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW2-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW3',
    txt_location = 'Guilford',
    txt_country = 'Great Britain',
    dt_start = '2024-01-04',
    dt_end = '2025-01-04',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/9CC8D1BC59084DC0852659F9B68D97DB#today',
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW3-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW4',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-01-05',
    dt_end = '2025-02-02',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW4-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW5',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-01-18',
    dt_end = '2025-03-15',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW5-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW6',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-02-01',
    dt_end = '2025-03-29',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW6-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW7',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-03-29',
    dt_end = '2025-05-15',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW7-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW8',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-03-30',
    dt_end = '2025-04-12',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW8-2024-2025';

UPDATE tbl_event SET
    txt_name = 'European Veterans Championships 2025',
    txt_location = 'Plovdiv',
    txt_country = 'Bulgaria',
    dt_start = '2025-05-28',
    dt_end = '2025-06-01',
    url_event = NULL,
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2025/04/invitation-ECH.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'IMEW-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PS',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-07-05',
    dt_end = '2025-07-05',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PS-2024-2025';

UPDATE tbl_event SET
    txt_name = 'PEW9',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2025-05-03',
    dt_end = '2025-05-03',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW9-2024-2025';

-- =========================================================================
-- Phase 3: PPW5 tournament result URLs (from FTL event schedule)
-- =========================================================================
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/344176CFFBD34C8684BD67F6D63BC4CE'
WHERE txt_code = 'PPW5-V0-M-SABRE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/577C8999CAD84E11AA8F65186E61F86A'
WHERE txt_code = 'PPW5-V1-M-EPEE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/5C623C9949DA4BFE9A3F6663E5074530'
WHERE txt_code = 'PPW5-V1-M-SABRE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/993817953DF94EE2BD3A86CEEF94CEF5'
WHERE txt_code = 'PPW5-V2-M-EPEE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/1B2C70B599F547299014C7E42AE198E6'
WHERE txt_code = 'PPW5-V3-F-FOIL-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/5126BA9976FE475CB4CDCC20DDA49EAF'
WHERE txt_code = 'PPW5-V3-F-SABRE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/958D6D51663A4F7E9464BCBC3167FF47'
WHERE txt_code = 'PPW5-V3-M-EPEE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/E81CCA279A6C47A09FDC7DA996157EA1'
WHERE txt_code = 'PPW5-V3-M-SABRE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/4C74F2EAEA2A46BBADE5609A4382C611'
WHERE txt_code = 'PPW5-V4-F-EPEE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/97261C8C2E0C4F5F91410EF344D7AC82'
WHERE txt_code = 'PPW5-V4-M-EPEE-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/7F63F67E2FD94C02A454586BC5F7F72E'
WHERE txt_code = 'PPW5-V4-M-FOIL-2024-2025';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/22021B5F31434144A94486A4C238DFDA'
WHERE txt_code = 'PPW5-V4-M-SABRE-2024-2025';
