-- =========================================================================
-- Event metadata for season 2023-2024
-- Auto-generated by staging_spreadsheet.py export mode.
-- Loaded AFTER per-category v*.sql files (zz_ prefix ensures ordering).
-- Phase 1: INSERT events not yet created by result files.
-- Phase 2: UPDATE all events with enriched metadata.
-- =========================================================================

-- Phase 1: Ensure all events exist
INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP1-2023-2024',
    'GP1',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP1-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP2-2023-2024',
    'GP2',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP2-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP3-2023-2024',
    'GP3',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP3-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP4-2023-2024',
    'GP4',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP4-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP5-2023-2024',
    'GP5',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP5-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP6-2023-2024',
    'GP6',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP6-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP7-2023-2024',
    'GP7',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP7-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'GP8-2023-2024',
    'GP8',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'GP8-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'MPW-2023-2024',
    'MPW',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'MPW-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW1-2023-2024',
    'PEW1',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW1-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW2-2023-2024',
    'PEW2',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW2-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW3-2023-2024',
    'PEW3',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW3-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW4-2023-2024',
    'PEW4',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW4-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW5-2023-2024',
    'PEW5',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW5-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW6-2023-2024',
    'PEW6',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW6-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW7-2023-2024',
    'PEW7',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW7-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW8-2023-2024',
    'PEW8',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW8-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW9-2023-2024',
    'PEW9',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW9-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW10-2023-2024',
    'PEW10',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW10-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW11-2023-2024',
    'PEW11',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW11-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW12-2023-2024',
    'PEW12',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW12-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'IMEW-2023-2024',
    'IMEW',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'IMEW-2023-2024');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'VFC-2023-2024',
    'VFC',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2023-2024'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'VFC-2023-2024');

-- Phase 2: Update events with enriched metadata
UPDATE tbl_event SET
    txt_name = 'GP1',
    txt_location = 'Pabianice',
    txt_country = 'Polska',
    dt_start = '2023-01-14',
    dt_end = '2023-01-15',
    url_event = 'https://www.fencingtimelive.com/tournaments/eventSchedule/B3DA380CD665461DA7201E30A5652557#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP1-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP2',
    txt_location = 'Toruń',
    txt_country = 'Polska',
    dt_start = '2023-03-04',
    dt_end = '2023-05-03',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/4A559DB9F1984325A771A6255602D540#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP2-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP3',
    txt_location = 'Niepołomice',
    txt_country = 'Polska',
    dt_start = '2022-06-18',
    dt_end = '2023-06-18',
    url_event = 'https://www.fencingtimelive.com/tournaments/eventSchedule/A233DC1D44A44F6CBC3CF3E9D9BDFBFA#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP3-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP4',
    txt_location = 'Opole',
    txt_country = 'Polska',
    dt_start = '2023-10-23',
    dt_end = '2023-10-23',
    url_event = 'https://www.fencingtimelive.com/tournaments/eventSchedule/4E8236D593B64434A9EE99D9B5F7E65F#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP4-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP5',
    txt_location = 'Gdańsk',
    txt_country = 'Polska',
    dt_start = '2023-10-28',
    dt_end = '2023-10-28',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/B039D94D12F243B1961DEA9CAB298A40#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP5-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP6',
    txt_location = 'Kraków',
    txt_country = 'Polska',
    dt_start = '2023-11-18',
    dt_end = '2023-11-18',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/B039D94D12F243B1961DEA9CAB298A40#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP6-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP7',
    txt_location = 'Spała',
    txt_country = 'Polska',
    dt_start = '2024-01-27',
    dt_end = '2024-01-28',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/7C79727B5303462D86F5E810E3BFD516#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP7-2023-2024';

UPDATE tbl_event SET
    txt_name = 'GP8',
    txt_location = 'Świdnica',
    txt_country = 'Polska',
    dt_start = '2024-06-22',
    dt_end = '2026-06-22',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/7C79727B5303462D86F5E810E3BFD516#today',
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'GP8-2023-2024';

UPDATE tbl_event SET
    txt_name = 'MPW',
    txt_location = 'Warszawa',
    txt_country = 'Polska',
    dt_start = '2024-03-02',
    dt_end = '2024-03-02',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = 100,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'MPW-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW1',
    txt_location = 'Guilford',
    txt_country = 'Great Britain',
    dt_start = '2023-01-07',
    dt_end = '2023-01-08',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/A49E0E562CE6460B82AACFD5C909F0BE#today',
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW1-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW2',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2022-01-08',
    dt_end = '2023-02-25',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW2-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW3',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-02-11',
    dt_end = '2023-12-02',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW3-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW4',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-03-18',
    dt_end = '2023-09-16',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW4-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW5',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-09-16',
    dt_end = '2023-09-24',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW5-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW6',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-11-11',
    dt_end = '2023-11-11',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW6-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW7',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-10-09',
    dt_end = '2023-12-16',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW7-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW8',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-12-16',
    dt_end = '2024-01-06',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW8-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW9',
    txt_location = 'Guildford',
    txt_country = 'Great Britain',
    dt_start = '2024-01-06',
    dt_end = '2024-02-24',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/1B776AA923B64D3FA61AB02233AF54BD#today',
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW9-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW10',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2024-01-20',
    dt_end = '2024-03-23',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW10-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW11',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2024-02-24',
    dt_end = '2024-04-06',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW11-2023-2024';

UPDATE tbl_event SET
    txt_name = 'PEW12',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-03-23',
    dt_end = '2024-04-27',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW12-2023-2024';

UPDATE tbl_event SET
    txt_name = 'IMEW',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-01-01',
    dt_end = '2023-01-01',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'IMEW-2023-2024';

UPDATE tbl_event SET
    txt_name = 'VFC',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = '2023-07-07',
    dt_end = '2023-07-07',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'VFC-2023-2024';
