-- =========================================================================
-- Event metadata for season 2025-2026
-- Auto-generated by staging_spreadsheet.py export mode.
-- Loaded AFTER per-category v*.sql files (zz_ prefix ensures ordering).
-- Phase 1: INSERT events not yet created by result files.
-- Phase 2: UPDATE all events with enriched metadata.
-- =========================================================================

-- Phase 1: Ensure all events exist
INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW1-2025-2026',
    'I Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW1-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW2-2025-2026',
    'II Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW2-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW3-2025-2026',
    'III Puchar Polski Weteranów / Warsaw Epee Open',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW3-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW4-2025-2026',
    'IV Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW4-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PPW5-2025-2026',
    'V Puchar Polski Weteranów',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'PLANNED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PPW5-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'MPW-2025-2026',
    'MPW',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'SPWS'),
    'PLANNED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'MPW-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW1-2025-2026',
    'EVF Circuit Budapest',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW1-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW2-2025-2026',
    'EVF Circuit Madrid',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW2-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW3-2025-2026',
    'EVF Circuit Guildford',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW3-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW4-2025-2026',
    'EVF Circuit Napoli',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW4-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW5-2025-2026',
    'EVF Circuit Stockholm',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW5-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW6-2025-2026',
    'EVF Circuit Jabłonna',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW6-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW7-2025-2026',
    'EVF Circuit Salzburg',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'PLANNED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW7-2025-2026');

INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW8-2025-2026',
    'EVF Circuit Chania',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'PLANNED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW8-2025-2026');


INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'IMSW-2025-2026',
    'IMSW',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'FIE'),
    'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'IMSW-2025-2026');


INSERT INTO tbl_event (txt_code, txt_name, id_season, id_organizer, enum_status)
SELECT
    'PEW9-2025-2026',
    'EVF Circuit Dublin',
    (SELECT id_season FROM tbl_season WHERE txt_code = 'SPWS-2025-2026'),
    (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF'),
    'PLANNED'
WHERE NOT EXISTS (SELECT 1 FROM tbl_event WHERE txt_code = 'PEW9-2025-2026');

-- Fix PS organizer: created by v*.sql with SPWS, should be EVF
UPDATE tbl_event SET id_organizer = (SELECT id_organizer FROM tbl_organizer WHERE txt_code = 'EVF')
WHERE txt_code = 'PEW10-2025-2026';

-- Phase 2: Update events with enriched metadata
-- Disable transition trigger for status corrections (generated v*.sql files may
-- set COMPLETED for events that haven't happened yet based on stale Excel dates)
ALTER TABLE tbl_event DISABLE TRIGGER trg_event_transition;
UPDATE tbl_event SET
    txt_name = 'I Puchar Polski Weteranów',
    txt_location = 'Opole',
    txt_country = 'Polska',
    dt_start = '2025-09-27',
    dt_end = '2025-09-28',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/BF6E1ADD88844A8CAC2F8CD353D082F9#today',
    url_invitation = 'https://weteraniszermierki.pl/zaproszenie-na-i-puchar-polski-weteranow-szermierki-opole-2025/',
    num_entry_fee = 250,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'PPW1-2025-2026';

UPDATE tbl_event SET
    txt_name = 'II Puchar Polski Weteranów',
    txt_location = 'Poznań',
    txt_country = 'Polska',
    dt_start = '2025-10-25',
    dt_end = '2025-10-26',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/BC4FAB2F4A5E466DAA8FC46EB73E50F6#today',
    url_invitation = 'https://weteraniszermierki.pl/wp-content/uploads/2025/10/Komunikat-zawodow-Poznan-2.pdf',
    num_entry_fee = 250,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'PPW2-2025-2026';

UPDATE tbl_event SET
    txt_name = 'III Puchar Polski Weteranów / Warsaw Epee Open',
    txt_location = 'Warszawa-Łomianki',
    txt_country = 'Polska',
    dt_start = '2025-12-13',
    dt_end = '2025-12-14',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/D099355BC4334343949BD91172023B49#today',
    url_invitation = 'https://weteraniszermierki.pl/zaproszenie-na-iii-puchar-polski-weteranow-szermierki-warsaw-epee-open-2025/',
    num_entry_fee = 250,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'PPW3-2025-2026';

UPDATE tbl_event SET
    txt_name = 'IV Puchar Polski Weteranów',
    txt_location = 'Gdańsk',
    txt_country = 'Polska',
    dt_start = '2026-02-21',
    dt_end = '2026-02-22',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/D586C1250E8C41D3BB9B9E5772CB998F#today',
    url_invitation = 'https://weteraniszermierki.pl/zaproszenie-na-iv-puchar-polski-weteranow-szermierki-gdansk-2026/',
    num_entry_fee = 250,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'PPW4-2025-2026';

UPDATE tbl_event SET
    txt_name = 'V Puchar Polski Weteranów',
    txt_location = 'Gdańsk',
    txt_country = 'Polska',
    enum_status = 'SCHEDULED',
    dt_start = '2026-04-11',
    dt_end = '2026-04-11',
    url_event = NULL,
    url_invitation = 'https://weteraniszermierki.pl/wp-content/uploads/2026/03/Komunikat-organizacyjny-V-Pucharu-Polski-Weteranow-Szermierki_Gdansk_11_kwietnia_2026.pdf',
    num_entry_fee = 250,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'PPW5-2025-2026';

UPDATE tbl_event SET
    txt_name = 'MPW',
    txt_location = 'Warszawa',
    txt_country = 'Polska',
    enum_status = 'SCHEDULED',
    dt_start = '2026-06-27',
    dt_end = '2026-06-28',
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = 250,
    txt_entry_fee_currency = 'PLN'
WHERE txt_code = 'MPW-2025-2026';

UPDATE tbl_event SET
    txt_name = 'EVF Circuit Budapest',
    txt_location = 'Budapest',
    txt_country = 'Hungary',
    dt_start = '2025-09-20',
    dt_end = '2025-09-21',
    url_event = 'https://engarde-service.com/tournament/hunfencing/2025_09_20_pbt',
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2025/08/International-Veteran-Budapest-Cup-event-2025-september-ENG.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW1-2025-2026';

UPDATE tbl_event SET
    txt_name = 'EVF Circuit Madrid',
    txt_location = 'Madrid',
    txt_country = 'Spain',
    dt_start = '2025-11-01',
    dt_end = '2025-11-02',
    url_event = 'https://engarde-service.com/tournament/aeve_esgrima/evf_madrid_2025',
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2025/10/EVF-Circuit-Madrid-2025.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW2-2025-2026';

UPDATE tbl_event SET
    txt_name = 'EVF Circuit Guildford',
    txt_location = 'Guildford',
    txt_country = 'Great Britain',
    dt_start = '2026-01-10',
    dt_end = '2026-01-11',
    url_event = 'https://fencingtimelive.com/tournaments/eventSchedule/E2A7B077F2824DD8A7F2E413B4211296#today',
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2025/10/EVf-Guildford-2026-invitation-letter.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW3-2025-2026';

UPDATE tbl_event SET
    txt_name = 'EVF Circuit Napoli',
    txt_location = 'Napoli',
    txt_country = 'Italy',
    dt_start = '2026-03-07',
    dt_end = '2026-03-08',
    url_event = 'https://www.4fence.it/FIS/Risultati/2026-03-08-07_Napoli_-_4_Prova_Circuito_Nazionale_Master_2025-2/',
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2026/01/EVF-Circuit-Napoli-7-and-8-mar26-ENG.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW4-2025-2026';

UPDATE tbl_event SET
    txt_name = 'EVF Circuit Stockholm',
    txt_location = 'Stockholm',
    txt_country = 'Sweden',
    dt_start = '2026-03-14',
    dt_end = '2026-03-14',
    url_event = 'https://engarde-service.com/tournament/sthlm/vet2026',
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2023/05/Invitation-EVF-Stockholm-2026.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW5-2025-2026';

UPDATE tbl_event SET
    txt_name = 'EVF Circuit Jabłonna',
    txt_location = 'Jabłonna',
    txt_country = 'Polska',
    dt_start = '2026-03-28',
    dt_end = '2026-03-29',
    url_event = 'https://www.fencingtimelive.com/tournaments/eventSchedule/98F13C10A47B49FFA2D39E4D47F1EDA8#today',
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2026/02/62c4d775-86d2-454c-9b61-c999e8d24791.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW6-2025-2026';

-- PEW7: 2026-04-18 — future event, seed files set COMPLETED from Excel data
UPDATE tbl_event SET
    txt_name = 'EVF Circuit Salzburg',
    txt_location = 'Salzburg',
    txt_country = 'Austria',
    enum_status = 'PLANNED',
    dt_start = '2026-04-18',
    dt_end = '2026-04-19',
    url_event = NULL,
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2026/03/EVC-Salzburg-Ausschreibung-2026_Aktuell-1.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW7-2025-2026';

-- PEW8: 2026-05-02 — future event
UPDATE tbl_event SET
    txt_name = 'EVF Circuit Chania',
    txt_location = 'Chania',
    txt_country = 'Greece',
    enum_status = 'PLANNED',
    dt_start = '2026-05-02',
    dt_end = '2026-05-03',
    url_event = NULL,
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2026/03/Chania-Invitation-letter-2026.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW8-2025-2026';


UPDATE tbl_event SET
    txt_name = 'EVF Criterium Mondial Vétérans 2025',
    txt_location = 'Paris',
    txt_country = 'France',
    dt_start = '2025-07-05',
    dt_end = '2025-07-05',
    url_event = 'https://engarde-service.com/tournament/fencingaddict/crit25',
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW10-2025-2026';

UPDATE tbl_event SET
    txt_name = 'IMSW',
    txt_location = NULL,
    txt_country = NULL,
    dt_start = NULL,
    dt_end = NULL,
    url_event = NULL,
    url_invitation = NULL,
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'IMSW-2025-2026';


UPDATE tbl_event SET
    txt_name = 'EVF Circuit Dublin',
    txt_location = 'Dublin',
    txt_country = 'Ireland',
    dt_start = '2026-05-30',
    dt_end = '2026-05-31',
    url_event = NULL,
    url_invitation = 'https://www.veteransfencing.eu/wp-content/uploads/2026/02/VIO-2026-Invitation-Letter.pdf',
    num_entry_fee = NULL,
    txt_entry_fee_currency = NULL
WHERE txt_code = 'PEW9-2025-2026';

-- Re-enable transition trigger
ALTER TABLE tbl_event ENABLE TRIGGER trg_event_transition;

-- =========================================================================
-- Phase 3: Populate PPW tournament result URLs
-- Scraped from FTL event schedule pages. PPW1 (Opole) has no FTL event page.
-- Combined categories (e.g., V3+V4) share the same FTL result UUID.
-- =========================================================================
-- PPW2 (Poznań)
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/C7FB3A80996945AE8AEBEE6DD63F6612'
WHERE txt_code = 'PPW2-V0-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/D8131FF685714FCD9BCE050A79E2EEE0'
WHERE txt_code = 'PPW2-V0-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/1C2782E9136D47B2BEAC8B8C1B64793E'
WHERE txt_code = 'PPW2-V0-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/869A24D618594CD199570470A5649341'
WHERE txt_code = 'PPW2-V0-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/0B63BC3174444722A28C41C02A5EE1E1'
WHERE txt_code = 'PPW2-V0-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/0B72604348914F89A732FA1D3BE4BC6B'
WHERE txt_code = 'PPW2-V0-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/DAE9230EA6EB44CD85ACEDD0E41E7B56'
WHERE txt_code = 'PPW2-V1-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/AD6B6C0FC2D64E879DB40A6720F33971'
WHERE txt_code = 'PPW2-V1-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/17C19116ADA6400E8190F4CA1C4DF400'
WHERE txt_code = 'PPW2-V1-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/270CBACF3FD84AFCACF159F56C41E27B'
WHERE txt_code = 'PPW2-V1-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/1C2F249657384463BC3978D922F692D1'
WHERE txt_code = 'PPW2-V1-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/DE023518560147FAB889108DB5DBC4A5'
WHERE txt_code = 'PPW2-V2-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/2C9CB7AA1DE74D8FB482A9E766D3B1C1'
WHERE txt_code = 'PPW2-V2-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/24E7B78B1B444A44966F1D0B46C21DE6'
WHERE txt_code = 'PPW2-V2-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/0387CC20A25B4EBA9BDAFAB148E8C12B'
WHERE txt_code = 'PPW2-V2-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/2D8E40AFE89C4AADB30969F1EA48CD4B'
WHERE txt_code = 'PPW2-V2-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/6610971D639346A5B221F97BDE81F295'
WHERE txt_code = 'PPW2-V3-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/1EE7810E56F14E65825123639583CA3E'
WHERE txt_code = 'PPW2-V3-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/901C7D026260410A8191318647544F22'
WHERE txt_code = 'PPW2-V3-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/49320988B9CF4996BBE48B4D78E1BB24'
WHERE txt_code = 'PPW2-V3-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/E633B73266C94E8B9E3AC691DBCFFEC4'
WHERE txt_code = 'PPW2-V3-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/938FCC269EE248BAA7DA16C234FCB039'
WHERE txt_code = 'PPW2-V4-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/C220C8FE06EF42FC9547F25555FD55D4'
WHERE txt_code = 'PPW2-V4-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/44623DC695434012AD5DE871225E2917'
WHERE txt_code = 'PPW2-V4-M-SABRE-2025-2026';
-- PPW3 (Warszawa / Łomianki)
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/652AC7E80652497FB5EB20653041EB49'
WHERE txt_code = 'PPW3-V0-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/8C9EB0FFE48241D6ABB5FB0E54475042'
WHERE txt_code = 'PPW3-V0-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/EE786DC009914DA2A4182A4632A91B8E'
WHERE txt_code = 'PPW3-V0-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/507479E25B594244937BDD375F7EB3D0'
WHERE txt_code = 'PPW3-V0-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/C8BF5C742C174649BA00F319CE2B3A58'
WHERE txt_code = 'PPW3-V0-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/DA82898DA1B84D5A9C8823E164845FA9'
WHERE txt_code = 'PPW3-V1-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/248068163F6D48F49953B9589A9227D8'
WHERE txt_code = 'PPW3-V1-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/02D923CB23224A869EC06D51D256BD16'
WHERE txt_code = 'PPW3-V2-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/CFB15D4643394134AF344160C6D97E4B'
WHERE txt_code = 'PPW3-V2-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/2034F718AC554C8D89A639B0EC0984DD'
WHERE txt_code = 'PPW3-V2-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/6FC6FCED7C4E4D1C95CA591801308B79'
WHERE txt_code = 'PPW3-V2-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/9AF3749A35A7461A8FE65962D92D8841'
WHERE txt_code = 'PPW3-V2-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/177F9E9257374C718E4A1C756F4079FC'
WHERE txt_code = 'PPW3-V3-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/6654BDFA4A1B4FCD9350C0D40E984C47'
WHERE txt_code = 'PPW3-V3-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/27A0E37B19C3432CA4FC325EA2B5A1A8'
WHERE txt_code = 'PPW3-V3-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/03D960BFD9E64ECEBAB9655EACBC1449'
WHERE txt_code = 'PPW3-V4-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/7D75E3CF201340FB84B1DAC6EA830212'
WHERE txt_code = 'PPW3-V4-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/A13C62B04392444983237CB85D62BB6B'
WHERE txt_code = 'PPW3-V4-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/905B54DECB20401EB47D299837F29C0A'
WHERE txt_code = 'PPW3-V4-M-SABRE-2025-2026';
-- PPW4 (Gdańsk) — scraped from D586C1250E8C41D3BB9B9E5772CB998F
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/48791095BA20459E8C815D9CA6070097'
WHERE txt_code = 'PPW4-V0-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/BA2A40142D714F9E97E298CCBF43AE12'
WHERE txt_code = 'PPW4-V0-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/F74D5C426B2542B0A81FC7EA51BECDA8'
WHERE txt_code = 'PPW4-V0-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/DA1C01B16745448E9716CE2AD252F9A2'
WHERE txt_code = 'PPW4-V0-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/4929E313891049FA9CF83C9DC9CECD3D'
WHERE txt_code = 'PPW4-V0-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/4793BEF489D848EDB24851784C0AC6D0'
WHERE txt_code = 'PPW4-V0-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/48791095BA20459E8C815D9CA6070097'
WHERE txt_code = 'PPW4-V1-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/BA2A40142D714F9E97E298CCBF43AE12'
WHERE txt_code = 'PPW4-V1-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/F74D5C426B2542B0A81FC7EA51BECDA8'
WHERE txt_code = 'PPW4-V1-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/DA1C01B16745448E9716CE2AD252F9A2'
WHERE txt_code = 'PPW4-V1-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/4929E313891049FA9CF83C9DC9CECD3D'
WHERE txt_code = 'PPW4-V1-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/4793BEF489D848EDB24851784C0AC6D0'
WHERE txt_code = 'PPW4-V1-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/B890129261D24AA998EA3E03351D659C'
WHERE txt_code = 'PPW4-V2-F-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/BA2A40142D714F9E97E298CCBF43AE12'
WHERE txt_code = 'PPW4-V2-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/F74D5C426B2542B0A81FC7EA51BECDA8'
WHERE txt_code = 'PPW4-V2-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/423C134004DD4536A8359CE636E743A1'
WHERE txt_code = 'PPW4-V2-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/4929E313891049FA9CF83C9DC9CECD3D'
WHERE txt_code = 'PPW4-V2-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/399A354C22224017B3C4CF59589C18D3'
WHERE txt_code = 'PPW4-V2-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/BA2A40142D714F9E97E298CCBF43AE12'
WHERE txt_code = 'PPW4-V3-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/F74D5C426B2542B0A81FC7EA51BECDA8'
WHERE txt_code = 'PPW4-V3-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/3AF4ABD141154089B037592935ED85CC'
WHERE txt_code = 'PPW4-V3-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/8B902817C0914EAF89D20A296314BDE3'
WHERE txt_code = 'PPW4-V3-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/42F2283CE3174AB18C720D2641D9B59F'
WHERE txt_code = 'PPW4-V3-M-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/BA2A40142D714F9E97E298CCBF43AE12'
WHERE txt_code = 'PPW4-V4-F-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/F74D5C426B2542B0A81FC7EA51BECDA8'
WHERE txt_code = 'PPW4-V4-F-SABRE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/9A47C75F59934E32982FECC78F6CD182'
WHERE txt_code = 'PPW4-V4-M-EPEE-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/8B902817C0914EAF89D20A296314BDE3'
WHERE txt_code = 'PPW4-V4-M-FOIL-2025-2026';
UPDATE tbl_tournament SET url_results = 'https://www.fencingtimelive.com/events/results/E8016D6001034325AD06A11ECAAC58B7'
WHERE txt_code = 'PPW4-V4-M-SABRE-2025-2026';
