#!/usr/bin/env node
/**
 * Generate frontend/src/lib/flags.generated.ts from the circle-flags package.
 *
 * Why generated-and-committed rather than imported at runtime:
 *   - `vite.config.ce.ts` sets no `base`, so any emitted asset URL resolves
 *     against the HOST page when the calendar is embedded cross-origin and
 *     404s. That is the bug already latent in SPWS-logo.png. Inline SVG has no
 *     URL to resolve.
 *   - Committing the output keeps `circle-flags` a devDependency: the build and
 *     CI never need it, and the flags cannot change under us without a diff.
 *
 * Every file in the package uses the same `mask id="a"`, so two flags on one
 * page would collide and one would render unmasked. The id is replaced with a
 * __ID__ token here and substituted per instance at render time.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = join(root, 'frontend/node_modules/circle-flags/flags')
const out = join(root, 'frontend/src/lib/flags.generated.ts')

const files = readdirSync(src).filter((f) => /^[a-z]{2}\.svg$/.test(f)).sort()

const entries = files.map((file) => {
  const iso = file.slice(0, 2).toUpperCase()
  let svg = readFileSync(join(src, file), 'utf8').trim()
  // Keep only what is inside <svg>: the wrapper is written by the component so
  // it controls size and accessibility.
  svg = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  // Unique-per-instance mask/clip ids.
  svg = svg.replace(/id="([a-zA-Z][\w-]*)"/g, (_m, id) => `id="${id}__ID__"`)
  svg = svg.replace(/url\(#([a-zA-Z][\w-]*)\)/g, (_m, id) => `url(#${id}__ID__)`)
  svg = svg.replace(/\s+/g, ' ').trim()
  return [iso, svg]
})

const body = entries.map(([iso, svg]) => `  ${iso}: ${JSON.stringify(svg)},`).join('\n')

writeFileSync(
  out,
  `// GENERATED by scripts/generate_flags.mjs — do not edit by hand.
// Source: circle-flags (MIT, HatScripts), ISO-3166 alpha-2 subset.
//
// Circular artwork removes the aspect-ratio problem that made hand-drawn flags
// wrong: Switzerland's flag is square and was being drawn in a 19x13 box with
// unequal arms, and Georgia was drawn as a plain red cross on white, which is
// England. Both are simply correct here, as is Greece's canton.
//
// \`__ID__\` is a placeholder: every source file reuses \`mask id="a"\`, so two
// flags on one page would collide. CountryFlag substitutes a per-instance id.

/** Inner SVG for each flag, on a 512x512 viewBox. */
export const FLAG_SVG: Record<string, string> = {
${body}
}

/** Every ISO code the set can draw — ${entries.length} countries. */
export const FLAG_CODES = Object.keys(FLAG_SVG)
`,
  'utf8',
)
console.log(`wrote ${entries.length} flags -> ${out}`)
