-- =============================================================================
-- Edit token — let a fencer correct a declaration they already submitted
-- =============================================================================
-- fn_create_registration decides "same person" by the DECLARED identity when
-- the entrant is unmatched, so re-submitting with a corrected spelling writes
-- a SECOND row instead of fixing the first. Proven on LOCAL 2026-08-28:
-- KOWALKSI Adam → row 18, KOWALSKI Adam → row 19, and row 18 stayed on the
-- public roster and in the organizer's seed file. Adding a forgotten weapon
-- already worked, because that leaves the arbiter untouched.
--
-- Updating by primary key consults no arbiter, so a correction rewrites the
-- row. What that needs is authorisation, and id_registration cannot provide
-- it: it is a column of vw_registration_entry_list — published, not merely
-- enumerable. Anyone could rewrite anyone's declaration.
--
-- So the capability is a token. The CLIENT generates it and keeps it; the
-- server only ever stores and compares it. That direction matters — the
-- function never has to hand a secret back, so fn_create_registration keeps
-- RETURNS INT and a cached older bundle goes on working, simply without an
-- edit capability.
--
-- Signature note: the new parameter is appended WITH A DEFAULT, so PostgREST's
-- named-argument calls from the currently deployed page still resolve. The old
-- signature is dropped rather than left beside the new one on purpose — two
-- overloads of one function is exactly what made the release fingerprint
-- non-deterministic in ba4ff3a, and one such trap is enough.
--
-- LAST WRITER WINS, and that is the whole mechanism. The token is a SHORT-LIVED
-- HANDLE, not a stored identity: it lives in the page's memory and is gone the
-- moment the form unmounts. A fencer coming back later re-enters the tuple they
-- declared, which upserts onto their row and mints them a fresh handle, and they
-- correct it from there. Without rotation a returning fencer could never obtain
-- a usable handle and the correction flow would dead-end, so this is required
-- rather than incidental.
--
-- The rejected alternative was persisting the handle in localStorage. It bought
-- one property — only the row's first registrant could rename it — and cost a
-- real one: localStorage is per-origin and per-device, so a fencer who
-- registered on a phone could not correct from a laptop, and register.html on
-- GitHub Pages and the CMS-embedded element cannot see each other's storage.
--
-- The accepted consequence: anyone who knows a declared name and birth year can
-- obtain the handle for that row and rename it. That is the same population who
-- can already overwrite the entry's weapons and gender through the ordinary
-- upsert (ADR-079 §4 accepts that), and the birth year is not the secret it
-- looks like — fn_match_registration_fencer is anon-callable and answers
-- per-year BEFORE any write, so it is already a free, silent oracle. Verified on
-- LOCAL: probing five years around a real fencer returned the id on the correct
-- one and NULL on the rest, leaving no row and no trace. Defending a guessable
-- secret at the cost of a real usability property was the wrong trade.
--
-- A caller that supplies NO token still never clears an existing one, so an
-- older cached bundle cannot wipe a live handle.
--
-- The real missing control is the rate limit ADR-079 §4 promises and nobody
-- built; it is tracked in doc/plans/registration-impersonation-posture-2026-08-28.html.
--
-- The token is not personal data, and no new personal data is collected, so
-- this is not a CONSENT_VERSION change. It supports the right to
-- rectification rather than widening what is held.
--
-- Plan-test-ID 59 (supabase/tests/59_registration_edit_handle.sql).
-- =============================================================================

BEGIN;

SET LOCAL lock_timeout = '2s';

-- 1. The capability column. Existing rows get one too, so anything already on
--    a live roster becomes correctable the moment its owner is handed a token
--    — though in practice their browser never kept one, so those remain an
--    organizer cleanup (see the 2026-08-28 plan).
ALTER TABLE tbl_registration
  ADD COLUMN IF NOT EXISTS uuid_edit_token UUID NOT NULL DEFAULT gen_random_uuid();

COMMENT ON COLUMN tbl_registration.uuid_edit_token IS
  'Capability for editing this registration. Generated by the client, stored '
  'here, never returned by any public projection — vw_registration_entry_list '
  'selects explicit columns and must never carry this one. Authorises '
  'fn_update_registration, which updates by primary key and so can change the '
  'declared name or birth year, which the create path cannot (they are its '
  'dedupe arbiter).';

-- 2. fn_create_registration — accept and retain a client-supplied token.
--    DROP + CREATE because the argument list changes; both statements are in
--    this transaction, so the function is never absent to a concurrent caller.
DROP FUNCTION IF EXISTS fn_create_registration(
  INT, TEXT, TEXT, enum_gender_type, SMALLINT, enum_weapon_type[], INT, TEXT, TEXT);

CREATE FUNCTION fn_create_registration(
  p_event           INT,
  p_surname         TEXT,
  p_first_name      TEXT,
  p_gender          enum_gender_type,
  p_birth_year      SMALLINT,
  p_weapons         enum_weapon_type[],
  p_id_fencer       INT DEFAULT NULL,
  p_email_hash      TEXT DEFAULT NULL,
  p_consent_version TEXT DEFAULT NULL,
  p_edit_token      UUID DEFAULT NULL
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id      INT;
  v_cutoff  DATE;
BEGIN
  SELECT COALESCE(dt_registration_deadline, dt_start) INTO v_cutoff
  FROM tbl_event WHERE id_event = p_event;

  IF v_cutoff IS NOT NULL AND now()::date > v_cutoff THEN
    RAISE EXCEPTION 'Registration window closed for event %', p_event;
  END IF;

  IF p_id_fencer IS NULL THEN
    -- Unmatched. A MATCHED row for this same declared identity means the
    -- lookup blipped rather than the entrant being new — update that row and
    -- keep its fencer link rather than writing an unlinked twin beside it.
    UPDATE tbl_registration SET
      txt_surname          = p_surname,
      txt_first_name       = p_first_name,
      enum_gender          = p_gender,
      arr_weapons          = p_weapons,
      txt_email_hash       = COALESCE(p_email_hash, txt_email_hash),
      ts_consent           = COALESCE(
                               CASE WHEN p_consent_version IS NOT NULL THEN now() END,
                               ts_consent),
      txt_consent_version  = COALESCE(p_consent_version, txt_consent_version),
      uuid_edit_token      = COALESCE(p_edit_token, uuid_edit_token)
    WHERE id_registration = (
      SELECT id_registration FROM tbl_registration
       WHERE id_event = p_event
         AND id_fencer IS NOT NULL
         AND upper(btrim(txt_surname))    = upper(btrim(p_surname))
         AND upper(btrim(txt_first_name)) = upper(btrim(p_first_name))
         AND int_birth_year               = p_birth_year
       ORDER BY id_registration
       LIMIT 1)
    RETURNING id_registration INTO v_id;

    IF v_id IS NOT NULL THEN
      RETURN v_id;
    END IF;

    INSERT INTO tbl_registration (
      id_event, id_fencer, txt_surname, txt_first_name, enum_gender,
      int_birth_year, arr_weapons, txt_email_hash,
      ts_consent, txt_consent_version, uuid_edit_token
    ) VALUES (
      p_event, NULL, p_surname, p_first_name, p_gender,
      p_birth_year, p_weapons, p_email_hash,
      CASE WHEN p_consent_version IS NOT NULL THEN now() END, p_consent_version,
      COALESCE(p_edit_token, gen_random_uuid())
    )
    ON CONFLICT (
      id_event,
      upper(btrim(txt_surname)),
      upper(btrim(txt_first_name)),
      int_birth_year
    ) WHERE id_fencer IS NULL DO UPDATE SET
      txt_surname          = EXCLUDED.txt_surname,
      txt_first_name       = EXCLUDED.txt_first_name,
      enum_gender          = EXCLUDED.enum_gender,
      arr_weapons          = EXCLUDED.arr_weapons,
      txt_email_hash       = COALESCE(EXCLUDED.txt_email_hash, tbl_registration.txt_email_hash),
      ts_consent           = COALESCE(EXCLUDED.ts_consent, tbl_registration.ts_consent),
      txt_consent_version  = COALESCE(EXCLUDED.txt_consent_version, tbl_registration.txt_consent_version),
      -- Rotate to the caller's handle. Only a caller that actually supplied one
      -- rotates it, so an older bundle re-submitting cannot wipe a live handle.
      uuid_edit_token      = COALESCE(p_edit_token, tbl_registration.uuid_edit_token)
    RETURNING id_registration INTO v_id;
  ELSE
    -- Matched. Absorb the unmatched twin first (see 20260828000002).
    IF EXISTS (
      SELECT 1 FROM tbl_registration
       WHERE id_event = p_event AND id_fencer = p_id_fencer
    ) THEN
      DELETE FROM tbl_registration
       WHERE id_event = p_event
         AND id_fencer IS NULL
         AND upper(btrim(txt_surname))    = upper(btrim(p_surname))
         AND upper(btrim(txt_first_name)) = upper(btrim(p_first_name))
         AND int_birth_year               = p_birth_year;
    ELSE
      UPDATE tbl_registration
         SET id_fencer = p_id_fencer
       WHERE id_event = p_event
         AND id_fencer IS NULL
         AND upper(btrim(txt_surname))    = upper(btrim(p_surname))
         AND upper(btrim(txt_first_name)) = upper(btrim(p_first_name))
         AND int_birth_year               = p_birth_year;
    END IF;

    INSERT INTO tbl_registration (
      id_event, id_fencer, txt_surname, txt_first_name, enum_gender,
      int_birth_year, arr_weapons, txt_email_hash,
      ts_consent, txt_consent_version, uuid_edit_token
    ) VALUES (
      p_event, p_id_fencer, p_surname, p_first_name, p_gender,
      p_birth_year, p_weapons, p_email_hash,
      CASE WHEN p_consent_version IS NOT NULL THEN now() END, p_consent_version,
      COALESCE(p_edit_token, gen_random_uuid())
    )
    ON CONFLICT (id_event, id_fencer) DO UPDATE SET
      txt_surname          = EXCLUDED.txt_surname,
      txt_first_name       = EXCLUDED.txt_first_name,
      enum_gender          = EXCLUDED.enum_gender,
      int_birth_year       = EXCLUDED.int_birth_year,
      arr_weapons          = EXCLUDED.arr_weapons,
      ts_consent           = COALESCE(EXCLUDED.ts_consent, tbl_registration.ts_consent),
      txt_consent_version  = COALESCE(EXCLUDED.txt_consent_version, tbl_registration.txt_consent_version),
      -- Rotate to the caller's handle. Only a caller that actually supplied one
      -- rotates it, so an older bundle re-submitting cannot wipe a live handle.
      uuid_edit_token      = COALESCE(p_edit_token, tbl_registration.uuid_edit_token)
    RETURNING id_registration INTO v_id;
  END IF;

  RETURN v_id;
END;
$$;

COMMENT ON FUNCTION fn_create_registration IS
  'Sole public CREATE path for tbl_registration (FR-122). Stamps consent when '
  'p_consent_version is given (D5); rejects the write once '
  'COALESCE(dt_registration_deadline, dt_start) has passed (D10). Upserts on '
  'UNIQUE(id_event, id_fencer) when matched and on the declared identity when '
  'not, absorbing the other branch''s twin first (2026-08-28). p_edit_token is '
  'retained but never rotated by a caller that did not supply one, so an older '
  'cached bundle cannot revoke a live edit capability. Correcting a declared '
  'name or birth year is NOT possible here — they are the unmatched arbiter, '
  'so a change reads as a different entrant; use fn_update_registration.';

-- 3. fn_update_registration — correct a declaration in place, by primary key.
--    No arbiter is consulted, so the declared name and birth year CAN change.
CREATE OR REPLACE FUNCTION fn_update_registration(
  p_id_registration INT,
  p_edit_token      UUID,
  p_surname         TEXT,
  p_first_name      TEXT,
  p_gender          enum_gender_type,
  p_birth_year      SMALLINT,
  p_weapons         enum_weapon_type[]
)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event   INT;
  v_cutoff  DATE;
BEGIN
  IF p_edit_token IS NULL THEN
    RAISE EXCEPTION 'Edit token required';
  END IF;

  -- Verify the capability and locate the event in one step. A wrong token and
  -- a non-existent row are deliberately indistinguishable to the caller.
  SELECT id_event INTO v_event
  FROM tbl_registration
  WHERE id_registration = p_id_registration
    AND uuid_edit_token = p_edit_token;

  IF v_event IS NULL THEN
    RAISE EXCEPTION 'Registration not found or edit token invalid';
  END IF;

  SELECT COALESCE(dt_registration_deadline, dt_start) INTO v_cutoff
  FROM tbl_event WHERE id_event = v_event;

  IF v_cutoff IS NOT NULL AND now()::date > v_cutoff THEN
    RAISE EXCEPTION 'Registration window closed for event %', v_event;
  END IF;

  -- Consent is deliberately untouched: it was given at submission, and
  -- correcting a typo is not a new consent event.
  BEGIN
    UPDATE tbl_registration SET
      txt_surname    = p_surname,
      txt_first_name = p_first_name,
      enum_gender    = p_gender,
      int_birth_year = p_birth_year,
      arr_weapons    = p_weapons
    WHERE id_registration = p_id_registration;
  EXCEPTION WHEN unique_violation THEN
    -- The corrected identity is already held by another entry at this event.
    -- Fail loudly: silently merging would destroy one of two real declarations.
    RAISE EXCEPTION 'Another registration for this event already declares that identity';
  END;

  RETURN p_id_registration;
END;
$$;

COMMENT ON FUNCTION fn_update_registration IS
  'Public EDIT path for tbl_registration, authorised by uuid_edit_token. '
  'Updates by primary key, so unlike fn_create_registration it can correct the '
  'declared name and birth year — those are the create path''s dedupe arbiter, '
  'where a change reads as a different entrant and inserts a second row. '
  'Enforces the same D10 window as the create path. Never changes id_fencer '
  '(the link is re-derived at ingestion, ADR-079 §3) and never restamps '
  'consent. Raises rather than merging when the corrected identity collides '
  'with another entry at the same event.';

GRANT EXECUTE ON FUNCTION fn_update_registration(
  INT, UUID, TEXT, TEXT, enum_gender_type, SMALLINT, enum_weapon_type[]) TO anon;
GRANT EXECUTE ON FUNCTION fn_update_registration(
  INT, UUID, TEXT, TEXT, enum_gender_type, SMALLINT, enum_weapon_type[]) TO authenticated;

COMMIT;
